### ISSUE TITLE
creator lacks some bitches and lives in concrete

### ISSUE THREAD

**Issue by COLONELBABBG** [royal0959/rafmod-pointtemplates-dump#1]
personally i think that is a very unhealthly lifestyle, you dont get much nutritions eating fucking rocks yeah? im worried about this project's future cause you may die soon

**Comment by royal0959** [comment]
sorry for the trouble. I've recently went and had sexual intercourse with your mother and moved toward living in the unused spaces in your antic rather than your walls. thanks for the report, cheers
